app:
  queue:
    patientQueue: "patientQueue"
    notificationQueue: "notificationQueue"

spring:
  activemq:
    broker-url:tcp://localhost: 61616
  datasource:
    url: jdbc:h2:mem:isildb;DB_CLOSE_DELAY=-1
    username: isil
    password: isil
  h2:
    console:
      enabled: true
server:
  port: 9000
