server:
  port: 9001

spring:
  activemq:
    broker-url: tcp://localhost:61616
  mail:
    username: abf7da7b6d7e00
    password: 436a17f6a730e4
    host: smtp.mailtrap.io
    port: 587
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  queue:
    notificationQueue: "notificationQueue"
